updated instructions
0xAX/linux-insides pull request #775
Opened 2021-05-10 01:31 UTC by cyruzin

I had some problems following the old instructions, some errors, so I made an update.

2021-05-10 04:37 UTC, initBasti commented on README.md
> +1. Enable Docker experimental features with vim or other text editor
s/or other text editor/or another text editor/

2021-05-10 04:50 UTC, initBasti commented on README.md
>     http://127.0.0.1:4000
This wasn't true for me, I had to explicitly use: `http://localhost:4000`
```bash
basti@basti-TUXEDO-Book-XA1510:~$ hostname -i
127.0.1.1
```
So, I would say we should use `http://localhost:4000`.

2021-05-10 04:51 UTC, initBasti commented on README.md
>  In order to run own copy of the book with gitook within local container:
While we are at it, let us fix those typos quickly:
s/run own copy/run your own copy/
s/gitook/gitbook/
s/within local container/within a local container/

2021-05-10 04:52 UTC, initBasti requested changes
I have tested your instructions and they work well, but I have found a few minor changes, that I would like to see fixed before merging this.
Thank you for your contribution!

2021-05-10 21:34 UTC, cyruzin commented
> I have tested your instructions and they work well, but I have found a few minor problems, that I would like to see fixed before merging this.
> Thank you for your contribution!

Sure, I'll update the PR.

2021-05-11 00:13 UTC, cyruzin commented
@initBasti done :)

2021-05-11 03:46 UTC, merged